export default {
  POSTS_PER_PAGE: 7,
  COMMENTS_PER_POST: 10,
  RESPONSES_PER_COMMENT: 10,
  CONTACT_USERS_PER_PAGE: 2,
  CONTACT_FRIENDS_PER_PAGE: 15,
  NUMBER_OF_MESSAGES_PER_LOAD: 15,
  NUMBER_CONVERSATIONS_LIMITATION: 10,
  NOTIFICATIONS_PER_PAGE: 7,
};
