export default {
  REACT_APP_POSTS_PER_PAGE: 7,
  REACT_APP_COMMENTS_PER_POST: 10,
  REACT_APP_RESPONSES_PER_COMMENT: 10,
  REACT_APP_NOTIFICATIONS_PER_PAGE: 20,
  REACT_APP_FETCH_MORE_NOTIFICATIONS_PER_PAGE: 10,
  REACT_APP_FRIENDS_PER_LOAD: 10,
  REACT_APP_USERS_CONTACT_PER_LOAD: 2,
  REACT_APP_CONTACT_USER_PER_PAGE: 10,
  REACT_APP_NUMBER_CONVERSATIONS_LIMITATION: 10,
  REACT_APP_NUMBER_MESSAGES_PER_LOAD: 15,
};
